// <auto-generated />
using GreenFinchAssignment.DataStructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace GreenFinchAssignment.Web.Migrations
{
    [DbContext(typeof(GreenFinchContext))]
    [Migration("20171120082655_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("GreenFinchAssignment.Web.Models.SubscribingSourceViewModel", b =>
                {
                    b.Property<int>("SubscribingSourceId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("SubscribingSourceId");

                    b.ToTable("SubscribingSource");
                });

            modelBuilder.Entity("GreenFinchAssignment.Web.Models.SubscribingUserViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("SubscribingReason");

                    b.Property<int>("SubscribingSourceId");

                    b.HasKey("Id");

                    b.ToTable("SubscribingUser");
                });
#pragma warning restore 612, 618
        }
    }
}
